name: Integração Contínua

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  execute_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v2

      - name: Instala o Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instala o Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Instala as Dependências
        run: poetry install

      - name: Executa o Black
        run: poetry run black app --check

      - name: Executa o Isort
        run: poetry run isort --check app/

      - name: Executa o Pydocstyle
        run: poetry run pydocstyle --check app/

      - name: Executa o Testes Unitários
        run: poetry run pytest
